baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Leyang Zou'
theme = "coder"

paginate = 20

#disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Leyang Zou"
  info = ["Computer Science Student", "@ University of Waterloo"]
  description = "Leyang Zou's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "PXL_20240106_181128516.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = false

  maxSeeAlsoItems = 5

  customCSS = ["style.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/BattleMage0231"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/leyang-zou-484137204/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 4
  url = "mailto:l2zou@uwaterloo.ca"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url  = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
